# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "httparty", "~> 0.18.1"

gem "rspec", "~> 3.10"

gem "ruby-progressbar", "~> 1.10"

gem "terminal-table", "~> 2.0"
