# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "httparty", "~> 0.18.1"

gem "rspec", "~> 3.10"

gem "ruby-progressbar", "~> 1.10"

gem "terminal-table", "~> 2.0"

gem "artii", "~> 2.1"

gem "tty-markdown", "~> 0.7.0"

gem "tty-prompt", "~> 0.23.0"

gem "tty-box", "~> 0.6.0"

gem "rainbow", "~> 3.0"

gem "tty-screen", "~> 0.8.1"
